feed:
    path: /
    controller: App\Controller\QuackController::getFeed

create:
    path: /create
    controller: App\Controller\QuackController::createOne

login:
    path: /login
    controller: App\Controller\DuckController::login

register:
    path: /register
    controller: App\Controller\RegistrationController::register