#index:
#    path: /
#    controller: App\Controller\DefaultController::index

feed:
    path: /feed
    controller: App\Controller\QuackController::getFeed

create:
    path: /create
    controller: App\Controller\QuackController:createOne
