create:
    path: /create
    controller: App\Controller\QuackController::createOne
    requirements:
        _method: POST

login:
    path: /login
    controller: App\Controller\DuckController::login

register:
    path: /register
    controller: App\Controller\RegistrationController::register

add_comment:
    path: /quack/{id}/comment/add
    controller: App\Controller\CommentController::add
    requirements:
        _method: POST

remove_comment:
    path: /comment/remove/{id}
    controller: App\Controller\CommentController::remove
    requirements:
        _method: DELETE

remove_quack:
    path: /quack/remove/{id}
    controller: App\Controller\QuackController::remove
    requirements:
        _method: DELETE